export const GET_USER_NOTIFICATION_REQUEST="GET_USER_NOTIFICATION_REQUEST"
export const GET_USER_NOTIFICATION_SUCCESS="GET_USER_NOTIFICATION_SUCCESS"
export const GET_USER_NOTIFICATION_FAILURE="GET_USER_NOTIFICATION_FAILURE"
export const RECEIVE_NOTIFICATION            = 'RECEIVE_NOTIFICATION';
export const CLEAR_NOTIFICATION_INDICATOR    = 'CLEAR_NOTIFICATION_INDICATOR';