export const LOGIN_USER_REQUEST="LOGIN_USER_REQUEST"
export const LOGIN_USER_SUCCESS="LOGIN_USER_SUCCESS"
export const LOGIN_USER_FAILURE="LOGIN_USER_FAILURE"

export const REGISTER_USER_REQUEST="REGISTER_USER_REQUEST"
export const REGISTER_USER_SUCCESS="REGISTER_USER_SUCCESS"
export const REGISTER_USER_FAILURE="REGISTER_USER_FAILURE"

export const GET_USER_PROFILE_REQUEST="GET_USER_PROFILE_REQUEST"
export const GET_USER_PROFILE_SUCCESS="GET_USER_PROFILE_SUCCESS"
export const GET_USER_PROFILE_FAILURE="GET_USER_PROFILE_FAILURE"

export const UPDATE_USER_REQUEST="UPDATE_USER_REQUEST"
export const UPDATE_USER_SUCCESS="UPDATE_USER_SUCCESS"
export const UPDATE_USER_FAILURE="UPDATE_USER_FAILURE"

export const FIND_USER_BY_ID_REQUEST="FIND_USER_BY_ID_REQUEST"
export const FIND_USER_BY_ID_SUCCESS="FIND_USER_BY_ID_SUCCESS"
export const FIND_USER_BY_ID_FAILURE="FIND_USER_BY_ID_FAILURE"

export const FOLLOW_USER_REQUEST="FOLLOW_USER_REQUEST"
export const FOLLOW_USER_SUCCESS="FOLLOW_USER_SUCCESS"
export const FOLLOW_USER_FAILURE="FOLLOW_USER_FAILURE"

export const SEND_EMAIL_VERIFICATION_REQUEST="SEND_EMAIL_VERIFICATION_REQUEST";
export const SEND_EMAIL_VERIFICATION_SUCCESS="SEND_EMAIL_VERIFICATION_SUCCESS";
export const SEND_EMAIL_VERIFICATION_FAILURE="SEND_EMAIL_VERIFICATION_FAILURE";

export const CHECK_EMAIL_EXISTED_REQUEST="CHECK_EMAIL_EXISTED_REQUEST";
export const CHECK_EMAIL_EXISTED_SUCCESS="CHECK_EMAIL_EXISTED_SUCCESS";
export const CHECK_EMAIL_EXISTED_FAILURE="CHECK_EMAIL_EXISTED_FAILURE";

export const CHANGE_PASSWORD_REQUEST="CHANGE_PASSWORD_REQUEST";
export const CHANGE_PASSWORD_SUCCESS="CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAILURE="CHANGE_PASSWORD_FAILURE";

export const FORGOT_PASSWORD_REQUEST="FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS="FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILURE="FORGOT_PASSWORD_FAILURE";

export const GET_USER_REQUEST="GET_USER_REQUEST";
export const GET_USER_SUCCESS="GET_USER_SUCCESS";
export const GET_USER_FAILURE="GET_USER_FAILURE";

export const LOGOUT="LOGOUT"