export const GET_DASHBOARD_ANALYTICS_SUCCESS="GET_DASHBOARD_ANALYTICS_SUCCESS";
export const GET_TWEET_ANALYTICS_SUCCESS="GET_TWEET_ANALYTICS_SUCCESS";
export const GET_LIKE_ANALYTICS_SUCCESS="GET_LIKE_ANALYTICS_SUCCESS";
export const GET_USER_ANALYTICS_SUCCESS="GET_USER_ANALYTICS_SUCCESS";
export const GET_ALL_USER_SUCCESS="GET_ALL_USER_SUCCESS";
export const BAN_USER_SUCCESS="BAN_USER_SUCCESS";
export const UNBAN_USER_SUCCESS="UNBAN_USER_SUCCESS";

export const GET_DASHBOARD_ANALYTICS_FAILURE="GET_DASHBOARD_ANALYTICS_FAILURE";
export const GET_TWEET_ANALYTICS_FAILURE="GET_TWEET_ANALYTICS_FAILURE";
export const GET_LIKE_ANALYTICS_FAILURE="GET_LIKE_ANALYTICS_FAILURE";
export const GET_USER_ANALYTICS_FAILURE="GET_USER_ANALYTICS_FAILURE";
export const GET_ALL_USER_FAILURE="GET_ALL_USER_FAILURE";
export const BAN_USER_FAILURE="BAN_USER_FAILURE";
export const UNBAN_USER_FAILURE="UNBAN_USER_FAILURE";

export const GET_DASHBOARD_ANALYTICS="GET_DASHBOARD_ANALYTICS";
export const GET_TWEET_ANALYTICS="GET_TWEET_ANALYTICS";
export const GET_LIKE_ANALYTICS="GET_LIKE_ANALYTICS";
export const GET_USER_ANALYTICS="GET_USER_ANALYTICS";
export const GET_ALL_USER="GET_ALL_USER";
export const BAN_USER="BAN_USER";
export const UNBAN_USER="UNBAN_USER";